jest.mock('../src/lib/query/actor-movie-query');
const { expect } = require('@jest/globals');
const getActorList = require('../src/lib/query/actor-movie-query');
const JohnnyDepp = require('./__mockData__/JohnnyDepp.json');

getActorList.mockImplementation((name) => {
  //splits name in actual implimentation.
  return JohnnyDepp.cast.map((object) => {
    return object.title;
  });
});

//limited responses based on what we expect from the API.

test('Gets the list based on the input name', async () => {
  const actorID = getActorList('Chris Pratt');
  const expected = [
    //expected data from the 'query'
    "Pirates of the Caribbean: Dead Man's Chest",
    'Edward Scissorhands',
    'Charlie and the Chocolate Factory',
    'Ed Wood',
    'The Ninth Gate',
    'From Hell',
    'Dead Man',
    'Finding Neverland',
    'Secret Window',
    "What's Eating Gilbert Grape",
    'Pirates of the Caribbean: On Stranger Tides',
    'Fear and Loathing in Las Vegas',
    'Don Juan DeMarco',
    'Nick of Time',
    'Sleepy Hollow',
    "The Astronaut's Wife",
    'Corpse Bride',
    'Blow',
    'Benny & Joon',
    'Arizona Dream',
    'Public Enemies',
    'The Rum Diary',
    'The Libertine',
    'Donnie Brasco',
    'Cry-Baby',
    'The Brave',
    'Sweeney Todd: The Demon Barber of Fleet Street',
    'The Tourist',
    'Dark Shadows',
    'Rango',
    'Private Resort',
    'The Lone Ranger',
    'Transcendence',
    'Pirates of the Caribbean: Dead Men Tell No Tales',
    'Mortdecai',
    'Black Mass',
    "Donald Trump's The Art of the Deal: The Movie",
    "Pirates of the Caribbean: At World's End",
    'Pirates of the Caribbean: The Curse of the Black Pearl',
    'The Professor',
    "When You're Strange",
    'Minamata',
    'Alice in Wonderland',
    'The Man Who Cried',
    'Alice Through the Looking Glass',
    'Sherlock Gnomes',
    'Hunter Goes to Hollywood',
    'City of Lies',
    'The Black Ghiandola',
    'Gonzo: The Life and Work of Dr. Hunter S. Thompson',
    'Waiting for the Barbarians',
    "Ed Wood: Let's Shoot This @#!%",
    'Rock and a Hard Place: Another Night at the Agora',
    'Kreka: Dreamcatcher',
    'Chocolat',
    'Once Upon a Time in Mexico',
    'Before Night Falls',
    'Deep Sea 3D',
    'Platoon',
    'It Came from... Baltimore!!',
    'Dark Shadows: The Collinses - Every Family Has Its Demons',
    'Alice in Wonderland: Finding Alice',
    'Alice in Wonderland: The Mad Hatter',
    'Spotlight on Location: Fear and Loathing in Las Vegas',
    "Live From Lincoln Center: Danny Elfman's Music from the Films of Tim Burton",
    "A Tour of the Inferno: Revisiting 'Platoon'",
    'Hollywood Vampires Live at Hellfest 2018',
    'Sleepy Hollow: Behind the Legend',
    'Charlie and the Chocolate Factory: Becoming Oompa-Loompa',
    'The Buried Secret of M. Night Shyamalan',
    'Donnie Brasco: Out of the Shadows',
    'Fantastic Beasts: The Crimes of Grindelwald',
    'Murder on the Orient Express',
    'London Fields',
    'Charlie and the Chocolate Factory: Attack of the Squirrels!',
    'Ed Wood: Pie Plates Over Hollywood',
    'Ed Wood: Making Bela',
    'Tusk',
    'The Source',
    'Breakfast with Hunter',
    'In Bad Taste',
    'Sweeney Todd: The Demon Barber of Fleet Street - Burton + Carter + Depp = Todd',
    'The Making of Edward Scissorhands',
    'A Nightmare on Elm Street',
    'The Imaginarium of Doctor Parnassus',
    'For No Good Reason',
    "Michael Mann: Making 'Public Enemies'",
    'Fantastic Beasts and Where to Find Them',
    'Gypsy Caravan: When the Road Bends',
    "Don't Say No Until I Finish Talking: The Story of Richard D. Zanuck",
    'Paradise Lost 3: Purgatory',
    'Ballybrando',
    'Crock of Gold: A Few Rounds With Shane MacGowan',
    'Into the Woods',
    'Hollywood Vampires: Rock in Rio 2015',
    "Freddy's Dead: The Final Nightmare",
    'Brando',
    'Buy the Ticket, Take the Ride',
    'Voom Portraits',
    'Pirates of the Caribbean: Tales of the Code – Wedlocked',
    'Slow Burn',
    'Lucky Them',
    'Yoga Hosers',
    "Kusturica - Balkan's Bad Boy",
    'Lost in La Mancha',
    'Charlie: The Life and Art of Charles Chaplin',
    'Don Rickles: One Night Only',
    'All the Love You Cannes!',
    'Cannes Man',
    'Jack and Jill',
    '21 Jump Street',
    'Happily Ever After',
    'Sunset Strip',
    'David Blaine: Beyond Magic',
    'Joe Strummer: The Future Is Unwritten',
    'L.A. Without a Map',
    'Never Sleep Again: The Elm Street Legacy',
    'The 90s: Ten Years That Changed the World',
  ];

  expect(actorID).toEqual(expected);
});
